### ISSUE TITLE
你好，WxRenderingContext、WxWebGLRenderingContext 等这些 api 确定官方文档有？

### ISSUE THREAD

**Issue by Pony-Unicorn** [jcyuan/wegame-api#3]
你好，WxRenderingContext、WxWebGLRenderingContext 等这些 api 确定官方文档有？

**Comment by jcyuan** [comment]
这不是API，这只是类型定义而已，和他们文档有没有并没有什么联系。
官方文档十分差，有很多错误。个人建议不要过多参考，除非他们大修改。

**Comment by Pony-Unicorn** [comment]
你不说我还以为是 api 呢，我都不知道什么是 dts 文件，你真厉害！
